logger:
  verbose: True

endpoint:
  postulant:
    dev: "https://{test_env}.aptitus.com/registro"
    pre: "https://{test_env}.aptitus.com/registro"
    prod: "https://aptitus.com/registro"

s3:
  input:
    bucket: qa.{env}
    key:  test/aptitus/{env}.{sub_env}/postulant/data/input

  output:
    bucket: qa.{env}
    key:  test/aptitus/{env}.{sub_env}/postulant/data/output
