
# TEST OPERATION

TEST_OPERATION_REGISTRO_RAPIDO = 'Registro Rapido de Postulante'

# SHEET
SHEET_REGISTRO = 'Registro'

# REQUEST COLUMNS
REQUEST_COLUMN_TXT_NAME = 0
REQUEST_COLUMN_TXT_FIRST_LAST_NAME = 1
REQUEST_COLUMN_TXT_SECOND_LAST_NAME = 2
REQUEST_COLUMN_TXT_EMAIL = 3
REQUEST_COLUMN_PSWD = 4
REQUEST_COLUMN_TXT_JOB = 5
REQUEST_COLUMN_SEL_LOCATION = 6

# Status Code HTTP
STATUS_CODE_503 = 503
